### ISSUE TITLE
Incorrect days

### ISSUE THREAD

**Issue by dalb8** [caarmen/FRCAndroidWidget#18]
Today is the 19th of July. According to Wikipedia, shouldn't we be on first day of Thermidor, Épautre and not on the last day of Messidor, Chalémie?

**Comment by caarmen** [comment]
Actually, there are (at least) two different methods to calculate the day.  This is a short summary of the methods:

* Equinox: The first day of each year is on the autumn equinox
* Romme: Each year is 365 days long, except for leap years, which have one extra day

I believe Wikipedia uses the Romme method.  The French calendar widget app supports both methods.  Open the settings and choose Romme instead of Equinox if you want to see the same date as Wikipedia

**Comment by caarmen** [comment]
In the Wikipedia article (https://en.wikipedia.org/wiki/French_Republican_Calendar ) there is a table in the "Converting from the Gregorian Calendar" which shows the first day of the year in each of the methods.  

You can see that for the 2014-2015 Gregorian year, the first day of the French Republican Calendar year is 22 September for the Romme method, and 23 September for the Equinox method, which explains this one day difference if you have the Equinox setting on the widget, and compare to the dates on the Wikipedia webpage.

**Comment by dalb8** [comment]
Ah! thanks for the explanation. In my defence, it has been many months since I looked at the Settings.

How about inserting the calculation method in the share text?


-------- Message d'origine --------
De : Carmen Alvarez <notifications@github.com>
Envoyé: 19 juillet 2015 13:04:22 UTC+01:00
À : caarmen/FRCAndroidWidget <FRCAndroidWidget@noreply.github.com>
Cc : dalb8 <daithi_black@yahoo.ie>
Objet : Re: [FRCAndroidWidget] Incorrect days (#18)

Closed #18.

---
Reply to this email directly or view it on GitHub:
https://github.com/caarmen/FRCAndroidWidget/issues/18#event-359430800
